include classpath("application.conf")

node-address {
  protocol = http
  host = elasticmq
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  vantage-judge-dlq {
    defaultVisibilityTimeout = 180 seconds
  }
  vantage-judge {
    defaultVisibilityTimeout = 180 seconds
    deadLettersQueue {
      name = "vantage-judge-dlq"
      maxReceiveCount = 3
    }
  }
}
